version: '3'

services:
        web:
                image: wildfly-web2
                ports: 
                        - "8080:8080"
                        - "9990:9990"
                volumes:
                        - ./deployments:/opt/jboss/wildfly/standalone/deployments/
                depends_on:
                        - db
        db:
                image: postgres:11
                ports: 
                        - "5432:5432"
                volumes:
                        - ./db_data:/var/lib/postgresql/data
